"""Tests for repo map generation and MCP resource integration."""

from pathlib import Path
from unittest.mock import patch

import pytest

from agenthub.auto.import_graph import ImportGraph
from agenthub.repo_map import generate_repo_map, generate_claude_md


@pytest.fixture
def map_project(tmp_path):
    """Create a project with enough structure to generate a meaningful map."""
    src = tmp_path / "src"
    src.mkdir()
    auth = src / "auth"
    auth.mkdir()
    models = src / "models"
    models.mkdir()
    api = src / "api"
    api.mkdir()
    utils = src / "utils"
    utils.mkdir()
    tests = tmp_path / "tests"
    tests.mkdir()

    # Core model used everywhere
    (models / "user.py").write_text(
        '''"""User model — core data structure."""
class User:
    def __init__(self, name, email):
        self.name = name
        self.email = email

    def to_dict(self):
        return {"name": self.name, "email": self.email}

class UserRole:
    ADMIN = "admin"
    USER = "user"

MAX_USERS = 1000
'''
    )

    # Utils used by many files
    (utils / "helpers.py").write_text(
        '''"""Shared helpers."""
from src.models.user import User

def format_user(user):
    return f"{user.name} <{user.email}>"

def validate_email(email):
    return "@" in email
'''
    )

    (utils / "dates.py").write_text(
        '''"""Date utilities."""
def parse_date(s):
    return s

def format_date(d):
    return str(d)
'''
    )

    # Auth depends on models
    (auth / "service.py").write_text(
        '''"""Auth service."""
from src.models.user import User, UserRole
from src.utils.helpers import validate_email

class AuthService:
    def login(self, email, password):
        if not validate_email(email):
            return None
        return User(email, email)

    def check_role(self, user, role):
        return True
'''
    )

    (auth / "middleware.py").write_text(
        '''"""Auth middleware."""
from src.auth.service import AuthService

def require_auth(handler):
    svc = AuthService()
    return handler
'''
    )

    # API depends on auth, models, utils
    (api / "routes.py").write_text(
        '''"""API routes."""
from src.auth.service import AuthService
from src.auth.middleware import require_auth
from src.models.user import User
from src.utils.helpers import format_user

def get_users():
    return []

def create_user(data):
    user = User(data["name"], data["email"])
    return format_user(user)
'''
    )

    (api / "admin.py").write_text(
        '''"""Admin routes."""
from src.models.user import User, UserRole
from src.auth.middleware import require_auth

def get_admin_panel():
    return "admin"
'''
    )

    # Tests
    (tests / "test_auth.py").write_text(
        '''"""Auth tests."""
from src.auth.service import AuthService

def test_login():
    svc = AuthService()
    assert svc.login("test@test.com", "pass") is not None
'''
    )

    (tests / "test_api.py").write_text(
        '''"""API tests."""
from src.api.routes import get_users, create_user

def test_get_users():
    assert get_users() == []
'''
    )

    return tmp_path


@pytest.fixture
def map_graph(map_project):
    g = ImportGraph(str(map_project))
    g.build()
    return g


class TestGenerateRepoMap:
    def test_contains_header(self, map_graph):
        result = generate_repo_map(map_graph)
        assert "## Repo Map (auto-generated by agenthub)" in result

    def test_contains_module_count(self, map_graph):
        result = generate_repo_map(map_graph)
        # Should mention the total module count
        assert "modules" in result

    def test_contains_key_modules(self, map_graph):
        result = generate_repo_map(map_graph)
        # user.py should be identified as a key module (many dependents)
        assert "user.py" in result

    def test_contains_directory_layout(self, map_graph):
        result = generate_repo_map(map_graph)
        assert "Directory layout" in result

    def test_contains_editing_guidance_for_hubs(self, map_graph):
        """If there are high-impact modules, editing guidance should appear."""
        result = generate_repo_map(map_graph)
        # The map should have at least the key modules section
        assert "Key modules" in result

    def test_respects_max_lines(self, map_graph):
        result = generate_repo_map(map_graph, max_lines=20)
        line_count = len(result.split("\n"))
        # Should be reasonably close to the limit (soft cap)
        assert line_count < 40  # Allow some overflow since it's a soft cap

    def test_shows_exports_for_hubs(self, map_graph):
        result = generate_repo_map(map_graph)
        # Hub modules should have their exports listed
        # user.py exports User, UserRole, to_dict etc.
        assert "User" in result


class TestGenerateClaudeMd:
    def test_contains_project_name(self, map_graph, map_project):
        result = generate_claude_md(map_graph, str(map_project))
        project_name = map_project.name
        assert project_name in result

    def test_contains_repo_map(self, map_graph, map_project):
        result = generate_claude_md(map_graph, str(map_project))
        assert "## Repo Map" in result

    def test_contains_workflow_instructions(self, map_graph, map_project):
        result = generate_claude_md(map_graph, str(map_project))
        assert "impact_check" in result
        assert "affected_tests" in result
        assert "preview_screenshot" in result

    def test_contains_before_editing_guidance(self, map_graph, map_project):
        result = generate_claude_md(map_graph, str(map_project))
        assert "Before editing" in result
        assert "After editing" in result


class TestMCPResourceIntegration:
    def test_resources_list(self):
        from agenthub.mcp_server import RESOURCES

        assert len(RESOURCES) == 1
        assert RESOURCES[0]["uri"] == "repo://map"
        assert RESOURCES[0]["mimeType"] == "text/markdown"

    def test_get_repo_map_returns_content(self, map_graph, map_project):
        from agenthub.mcp_server import get_repo_map

        with patch("agenthub.mcp_server.get_graph", return_value=map_graph):
            result = get_repo_map()

        # Reset cache for other tests
        import agenthub.mcp_server as mcp
        mcp._repo_map_cache = None

        assert result is not None
        assert "Repo Map" in result
        assert "modules" in result

    def test_get_repo_map_caches(self, map_graph):
        from agenthub.mcp_server import get_repo_map
        import agenthub.mcp_server as mcp

        mcp._repo_map_cache = None

        with patch("agenthub.mcp_server.get_graph", return_value=map_graph):
            result1 = get_repo_map()
            # Second call should use cache (get_graph won't be called)
            with patch("agenthub.mcp_server.get_graph", return_value=None):
                result2 = get_repo_map()

        assert result1 == result2

        # Cleanup
        mcp._repo_map_cache = None

    def test_get_repo_map_no_graph(self):
        from agenthub.mcp_server import get_repo_map
        import agenthub.mcp_server as mcp

        mcp._repo_map_cache = None

        with patch("agenthub.mcp_server.get_graph", return_value=None):
            result = get_repo_map()

        assert result is None


class TestCLIMapCommand:
    def test_stdout_flag(self, map_project):
        """Test that --stdout prints to stdout instead of writing file."""
        import argparse

        from agenthub.cli import cmd_map

        args = argparse.Namespace(path=str(map_project), stdout=True, verbose=False)

        # Should succeed (return 0)
        result = cmd_map(args)
        assert result == 0

        # Should NOT create CLAUDE.md when using --stdout
        claude_md = map_project / "CLAUDE.md"
        assert not claude_md.exists()

    def test_creates_claude_md(self, map_project):
        """Test that running without --stdout creates CLAUDE.md."""
        import argparse

        from agenthub.cli import cmd_map

        args = argparse.Namespace(path=str(map_project), stdout=False, verbose=False)

        result = cmd_map(args)
        assert result == 0

        claude_md = map_project / "CLAUDE.md"
        assert claude_md.exists()
        content = claude_md.read_text()
        assert "Repo Map" in content
        assert "impact_check" in content

    def test_appends_to_existing_claude_md(self, map_project):
        """If CLAUDE.md exists, append the repo map."""
        import argparse

        from agenthub.cli import cmd_map

        # Create existing CLAUDE.md
        claude_md = map_project / "CLAUDE.md"
        claude_md.write_text("# My Project\n\nExisting content here.\n")

        args = argparse.Namespace(path=str(map_project), stdout=False, verbose=False)
        result = cmd_map(args)
        assert result == 0

        content = claude_md.read_text()
        assert "Existing content here." in content
        assert "Repo Map" in content

    def test_updates_existing_repo_map(self, map_project):
        """If CLAUDE.md already has a repo map, replace it."""
        import argparse

        from agenthub.cli import cmd_map

        # Create existing CLAUDE.md with old repo map
        claude_md = map_project / "CLAUDE.md"
        claude_md.write_text(
            "# My Project\n\n"
            "## Repo Map (auto-generated by agenthub)\n\n"
            "OLD CONTENT\n\n"
            "## Other Section\n\nKeep this.\n"
        )

        args = argparse.Namespace(path=str(map_project), stdout=False, verbose=False)
        result = cmd_map(args)
        assert result == 0

        content = claude_md.read_text()
        assert "OLD CONTENT" not in content
        assert "Other Section" in content
        assert "Keep this." in content
        assert "Repo Map" in content
