"""AgentHub CLI.

Commands:
    agenthub map          - Generate repo-aware CLAUDE.md from dependency graph
    agenthub map --stdout - Print to stdout instead of writing file

Example:
    $ agenthub map               # Generate CLAUDE.md in current directory
    $ agenthub map /path/to/dir  # Generate for specific project
    $ agenthub map --stdout      # Print repo map without writing file
"""

import argparse
import os
import sys
from pathlib import Path


def _setup_path():
    """Ensure agenthub is importable."""
    src_path = Path(__file__).parent.parent
    if str(src_path) not in sys.path:
        sys.path.insert(0, str(src_path))


def cmd_map(args):
    """Map command - generate a repo-aware CLAUDE.md from the dependency graph."""
    _setup_path()

    project_root = args.path or os.getcwd()
    project_root = os.path.abspath(project_root)

    if not os.path.isdir(project_root):
        print(f"Error: '{project_root}' is not a valid directory")
        return 1

    project_name = Path(project_root).name

    print(f"Analyzing {project_name}...", file=sys.stderr)

    try:
        from agenthub.auto.import_graph import ImportGraph
        from agenthub.repo_map import generate_claude_md, generate_repo_map

        graph = ImportGraph(project_root)
        graph.build()
        stats = graph.get_stats()
        print(f"  {stats['total_modules']} modules, {stats['total_edges']} dependencies", file=sys.stderr)

        if args.stdout:
            print(generate_claude_md(graph, project_root))
            return 0

        # Write CLAUDE.md
        output_path = Path(project_root) / "CLAUDE.md"
        existing_content = ""

        if output_path.exists():
            existing_content = output_path.read_text(encoding="utf-8")

            # Check if it already has an auto-generated section
            marker = "## Repo Map (auto-generated by agenthub)"
            if marker in existing_content:
                # Replace just the repo map section
                before = existing_content.split(marker)[0].rstrip()
                after_map = existing_content.split(marker)[1]
                next_heading = after_map.find("\n## ")
                if next_heading != -1:
                    after = after_map[next_heading:]
                else:
                    after = ""

                repo_map = generate_repo_map(graph)
                new_content = before + "\n\n" + repo_map + after
                output_path.write_text(new_content, encoding="utf-8")
                print(f"Updated repo map in: {output_path}")
                return 0

            # Append to existing CLAUDE.md
            repo_map = generate_repo_map(graph)
            new_content = existing_content.rstrip() + "\n\n" + repo_map + "\n"
            output_path.write_text(new_content, encoding="utf-8")
            print(f"Appended repo map to: {output_path}")
        else:
            # Create new CLAUDE.md
            content = generate_claude_md(graph, project_root)
            output_path.write_text(content, encoding="utf-8")
            print(f"Created: {output_path}")

        return 0

    except Exception as e:
        print(f"Error: {e}")
        if hasattr(args, 'verbose') and args.verbose:
            import traceback
            traceback.print_exc()
        return 1


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="agenthub",
        description="AgentHub - Impact analysis for Claude Code",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  map   Generate repo-aware CLAUDE.md from dependency graph

Examples:
  agenthub map               # Generate CLAUDE.md with repo map
  agenthub map --stdout      # Print repo map without writing file
  agenthub map /path/to/dir  # Generate for specific project
        """
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose output"
    )

    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Map command
    map_parser = subparsers.add_parser(
        "map",
        help="Generate repo-aware CLAUDE.md from dependency graph"
    )
    map_parser.add_argument(
        "path",
        nargs="?",
        help="Project root path (default: current directory)"
    )
    map_parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing CLAUDE.md"
    )
    map_parser.set_defaults(func=cmd_map)

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 0

    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
