"""Generate a concise repo map from the import graph.

The repo map is designed to be injected into CLAUDE.md or served as an MCP
resource so that every Claude Code agent (including parallel subagents) has
repo-specific context without needing to call a tool first.

The output is deliberately concise — it must fit comfortably within a system
prompt without consuming too much of the context window.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agenthub.auto.import_graph import ImportGraph


def generate_repo_map(graph: "ImportGraph", max_lines: int = 80) -> str:
    """Generate a concise repo map from the import graph.

    Args:
        graph: A built ImportGraph instance.
        max_lines: Soft cap on output lines to keep it context-friendly.

    Returns:
        Markdown-formatted repo map suitable for CLAUDE.md or MCP resource.
    """
    if not graph._built:
        graph.build()

    stats = graph.get_stats()
    hubs = graph.get_central_modules(top_n=15)

    lines: list[str] = []
    lines.append("## Repo Map (auto-generated by agenthub)")
    lines.append("")

    # --- Overview ---
    lang_parts = []
    if stats.get("python_modules"):
        lang_parts.append(f"Python: {stats['python_modules']}")
    if stats.get("typescript_modules"):
        lang_parts.append(f"TypeScript: {stats['typescript_modules']}")
    if stats.get("javascript_modules"):
        lang_parts.append(f"JavaScript: {stats['javascript_modules']}")

    lines.append(f"{stats['total_modules']} modules | {stats['total_edges']} dependencies | {' | '.join(lang_parts)}")
    lines.append("")

    # --- Hub modules (high-risk, high-impact) ---
    if hubs:
        lines.append("### Key modules (most depended-on)")
        lines.append("")
        for hub_path in hubs:
            node = graph.nodes.get(hub_path)
            if not node:
                continue
            n_importers = len(node.imported_by)
            role = graph.get_module_role(hub_path)

            # Get exported interface summary (compact)
            interface = graph.get_exported_interface(hub_path)
            exports = []
            for cls in interface.get("classes", [])[:3]:
                exports.append(cls["name"])
            for func in interface.get("functions", [])[:3]:
                exports.append(f"{func['name']}()")
            export_str = ", ".join(exports) if exports else ""

            risk = "HIGH IMPACT" if n_importers >= 10 else "medium" if n_importers >= 4 else ""
            risk_str = f" **{risk}**" if risk else ""

            lines.append(f"- `{hub_path}` ({n_importers} dependents){risk_str}")
            if export_str:
                lines.append(f"  Exports: {export_str}")

            if len(lines) > max_lines - 20:
                break
        lines.append("")

    # --- Dependency chains ---
    # Find the most important dependency paths (hub -> hub connections)
    hub_set = set(hubs) if hubs else set()
    chains: list[str] = []
    seen_chains: set[str] = set()

    for hub_path in (hubs or [])[:8]:
        node = graph.nodes.get(hub_path)
        if not node:
            continue
        for dep in node.imports:
            if dep in hub_set and dep != hub_path:
                chain_key = f"{_short(hub_path)} -> {_short(dep)}"
                reverse_key = f"{_short(dep)} -> {_short(hub_path)}"
                if chain_key not in seen_chains and reverse_key not in seen_chains:
                    chains.append(chain_key)
                    seen_chains.add(chain_key)

    if chains:
        lines.append("### Key dependency chains")
        lines.append("")
        for chain in chains[:10]:
            lines.append(f"- {chain}")
        lines.append("")

    # --- Directory structure (top-level folders with module counts) ---
    folder_counts: dict[str, int] = {}
    for path in graph.nodes:
        parts = Path(path).parts
        if len(parts) >= 3:
            folder = parts[0] + "/" + parts[1]
        elif len(parts) == 2:
            folder = parts[0]
        else:
            folder = "(root)"
        folder_counts[folder] = folder_counts.get(folder, 0) + 1

    if folder_counts:
        # Sort by count, show top folders
        sorted_folders = sorted(folder_counts.items(), key=lambda x: -x[1])
        lines.append("### Directory layout")
        lines.append("")
        for folder, count in sorted_folders[:15]:
            lines.append(f"- `{folder}/` ({count} modules)")

            if len(lines) > max_lines - 5:
                break
        lines.append("")

    # --- Editing guidance ---
    high_impact = [h for h in (hubs or []) if len(graph.nodes[h].imported_by) >= 8]
    if high_impact:
        lines.append("### Editing guidance")
        lines.append("")
        lines.append("These files have many dependents. Changing their interface (function signatures,")
        lines.append("class methods, exports) will break downstream code. Always check dependents first:")
        lines.append("")
        for path in high_impact[:5]:
            n = len(graph.nodes[path].imported_by)
            lines.append(f"- `{path}` ({n} dependents)")
        lines.append("")

    return "\n".join(lines)


def generate_claude_md(graph: "ImportGraph", project_root: str) -> str:
    """Generate a complete CLAUDE.md with repo map and workflow instructions.

    Args:
        graph: A built ImportGraph instance.
        project_root: Path to the project root.

    Returns:
        Full CLAUDE.md content.
    """
    project_name = Path(project_root).name
    repo_map = generate_repo_map(graph)

    sections = [
        f"# {project_name}",
        "",
        repo_map,
        "## Workflow",
        "",
        "### Before editing files",
        "Call the `impact_check` MCP tool with the file path.",
        "If risk is HIGH, preserve the exported interface — do not rename functions,",
        "change signatures, or remove classes without also updating all listed dependents.",
        "",
        "### After editing files",
        "Call `affected_tests` with all changed file paths.",
        "Run the suggested test command. Fix failures before moving on.",
        "",
        "### Frontend changes",
        "After modifying .tsx/.jsx/.vue/.svelte/.css files, use `preview_screenshot`",
        "to verify rendered output. Do not assume CSS changes are correct without checking.",
        "",
    ]

    return "\n".join(sections)


def _short(path: str) -> str:
    """Shorten a path for display (e.g. src/auth/service.py -> auth/service)."""
    p = Path(path)
    # Drop common prefixes
    parts = list(p.parts)
    if parts and parts[0] in ("src", "lib", "app"):
        parts = parts[1:]
    # Drop extension
    if parts:
        parts[-1] = Path(parts[-1]).stem
    return "/".join(parts) if parts else path
