from __future__ import annotations
"""AgentHub setup utilities for API keys, MCP config, and project configuration.

One-command setup:
    $ agenthub init              # Initialize AgentHub in current directory
    $ agenthub init /path/to/dir # Initialize in specific directory

This module handles:
- One-command project initialization
- Checking and prompting for API keys
- Storing project path in global config
- Generating MCP configuration for Claude Code
"""

import json
import os
import sys
from pathlib import Path
from typing import Optional


# =============================================================================
# Templates for generated files
# =============================================================================

AGENTS_FILE_TEMPLATE = '''"""AgentHub agents for {project_name}.

Auto-generated by `agenthub init`. Customize this file to add domain-specific agents.

Usage:
    from {module_name} import create_hub

    hub = create_hub()
    response = hub.run("How does authentication work?")

    # Or use parallel execution for multi-part requests:
    hub = create_hub(enable_parallel=True)
    result = hub.execute_parallel("Add login form and signup page")
"""

from agenthub import AgentHub
from agenthub.auto import AutoAgentConfig, discover_all_agents


def create_hub(
    project_root: str = ".",
    enable_parallel: bool = False,
) -> AgentHub:
    """Create an AgentHub configured for this project.

    Args:
        project_root: Path to the project root.
        enable_parallel: Enable parallel session execution.

    Returns:
        Configured AgentHub instance.
    """
    config = AutoAgentConfig(
        min_folder_size_kb=10,
        min_files_per_folder=2,
        max_agent_context_kb=80,
        max_depth=4,
        ignore_patterns={ignore_patterns},
    )

    hub, summary = discover_all_agents(project_root, config=config)
    print(summary)

    if enable_parallel:
        from agenthub.parallel import ParallelExecutionConfig
        hub.enable_parallel_sessions(
            project_root,
            config=ParallelExecutionConfig(max_parallel_sessions=3),
        )
        print("Parallel sessions enabled")

    return hub


if __name__ == "__main__":
    import os
    from agenthub.auto import print_agent_tree

    project_path = os.path.dirname(os.path.abspath(__file__))
    hub = create_hub(project_path)

    print("\\n" + "=" * 60)
    print("{project_name} AgentHub Ready")
    print("=" * 60)
    print("\\nAgent Hierarchy:")
    print(print_agent_tree(hub, "{project_name_lower}"))
'''

AGENTHUBIGNORE_TEMPLATE = """# AgentHub ignore patterns
# Files matching these patterns will be excluded from agent analysis

# Dependencies
node_modules/
.venv/
venv/
__pycache__/
*.egg-info/

# Build artifacts
dist/
build/
.next/
coverage/

# IDE and system
.git/
.idea/
.vscode/
*.pyc
*.pyo
.DS_Store

# Test and cache
.pytest_cache/
.mypy_cache/
.tox/
htmlcov/

# Logs and temp
*.log
*.tmp
.env.local
"""

# Global config location
AGENTHUB_CONFIG_DIR = Path.home() / ".agenthub"
AGENTHUB_CONFIG_FILE = AGENTHUB_CONFIG_DIR / "config.json"

# Claude Code MCP config location
CLAUDE_CONFIG_FILE = Path.home() / ".claude.json"


def get_config() -> dict:
    """Load AgentHub global config."""
    if AGENTHUB_CONFIG_FILE.exists():
        try:
            with open(AGENTHUB_CONFIG_FILE) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_config(config: dict) -> None:
    """Save AgentHub global config."""
    AGENTHUB_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with open(AGENTHUB_CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)


def get_current_project() -> Optional[str]:
    """Get the currently configured project path."""
    config = get_config()
    return config.get("project")


def set_current_project(project_path: str) -> None:
    """Set the current project path."""
    config = get_config()
    config["project"] = str(Path(project_path).resolve())
    save_config(config)


def check_api_keys(project_path: str) -> dict:
    """Check for API keys in environment and .env files.

    Returns:
        Dict with 'anthropic' and 'openai' keys, each True/False.
    """
    from agenthub.config import load_env_files

    # Load .env files
    load_env_files(verbose=False)

    # Also try project-specific .env
    project_env = Path(project_path) / ".env"
    if project_env.exists():
        from dotenv import load_dotenv
        load_dotenv(project_env, override=True)

    return {
        "anthropic": bool(os.environ.get("ANTHROPIC_API_KEY")),
        "openai": bool(os.environ.get("OPENAI_API_KEY")),
    }


def prompt_for_api_key(project_path: str) -> bool:
    """Prompt user to enter API key if missing.

    Returns:
        True if at least one API key is now available.
    """
    keys = check_api_keys(project_path)

    if keys["anthropic"] or keys["openai"]:
        return True

    print()
    print("No API keys found!")
    print("-" * 40)
    print("AgentHub needs at least one API key to work.")
    print()
    print("Options:")
    print("  1. Enter ANTHROPIC_API_KEY now")
    print("  2. Enter OPENAI_API_KEY now")
    print("  3. Skip (I'll set it up manually)")
    print()

    choice = input("Choose [1/2/3]: ").strip()

    if choice == "1":
        api_key = input("Enter ANTHROPIC_API_KEY: ").strip()
        if api_key:
            _save_api_key_to_env(project_path, "ANTHROPIC_API_KEY", api_key)
            os.environ["ANTHROPIC_API_KEY"] = api_key
            print("Saved to .env file")
            return True
    elif choice == "2":
        api_key = input("Enter OPENAI_API_KEY: ").strip()
        if api_key:
            _save_api_key_to_env(project_path, "OPENAI_API_KEY", api_key)
            os.environ["OPENAI_API_KEY"] = api_key
            print("Saved to .env file")
            return True
    elif choice == "3":
        print()
        print("Manual setup instructions:")
        print(f"  1. Create {project_path}/.env")
        print("  2. Add: ANTHROPIC_API_KEY=your-key-here")
        print("  3. Run 'agenthub build' again")
        return False

    return False


def _save_api_key_to_env(project_path: str, key_name: str, key_value: str) -> None:
    """Save an API key to the project's .env file."""
    env_file = Path(project_path) / ".env"

    # Read existing content
    existing_lines = []
    if env_file.exists():
        with open(env_file) as f:
            existing_lines = f.readlines()

    # Check if key already exists
    key_found = False
    new_lines = []
    for line in existing_lines:
        if line.strip().startswith(f"{key_name}="):
            new_lines.append(f"{key_name}={key_value}\n")
            key_found = True
        else:
            new_lines.append(line)

    # Add key if not found
    if not key_found:
        if new_lines and not new_lines[-1].endswith("\n"):
            new_lines.append("\n")
        new_lines.append(f"{key_name}={key_value}\n")

    # Write back
    with open(env_file, "w") as f:
        f.writelines(new_lines)


def get_agenthub_src_path() -> str:
    """Get the path to AgentHub's src directory."""
    # This file is in src/agenthub/setup.py
    return str(Path(__file__).parent.parent.resolve())


def generate_mcp_config(project_path: str) -> dict:
    """Generate MCP server configuration for Claude Code.

    Args:
        project_path: Path to the project to configure.

    Returns:
        MCP server config dict.
    """
    src_path = get_agenthub_src_path()
    project_path = str(Path(project_path).resolve())

    # Determine python command
    python_cmd = sys.executable

    return {
        "command": python_cmd,
        "args": ["-m", "agenthub.mcp_server", "--project", project_path],
        "env": {
            "PYTHONPATH": src_path,
        }
    }


def update_claude_config(project_path: str) -> bool:
    """Update Claude Code's MCP configuration.

    Args:
        project_path: Path to the project.

    Returns:
        True if config was updated successfully.
    """
    mcp_config = generate_mcp_config(project_path)

    # Load existing Claude config
    claude_config = {}
    if CLAUDE_CONFIG_FILE.exists():
        try:
            with open(CLAUDE_CONFIG_FILE) as f:
                claude_config = json.load(f)
        except Exception:
            pass

    # Ensure mcpServers exists
    if "mcpServers" not in claude_config:
        claude_config["mcpServers"] = {}

    # Update agenthub config
    claude_config["mcpServers"]["agenthub"] = mcp_config

    # Write back
    try:
        with open(CLAUDE_CONFIG_FILE, "w") as f:
            json.dump(claude_config, f, indent=2)
        return True
    except Exception as e:
        print(f"Error updating Claude config: {e}")
        return False


def print_mcp_config(project_path: str) -> None:
    """Print the MCP configuration for manual setup."""
    config = generate_mcp_config(project_path)

    print()
    print("MCP Configuration for Claude Code:")
    print("-" * 40)
    print(f"Add this to {CLAUDE_CONFIG_FILE}:")
    print()
    print(json.dumps({"mcpServers": {"agenthub": config}}, indent=2))
    print()


def setup_mcp_config(project_path: str, auto: bool = False) -> bool:
    """Set up MCP configuration, optionally prompting user.

    Args:
        project_path: Path to the project.
        auto: If True, automatically update without prompting.

    Returns:
        True if MCP was configured.
    """
    if auto:
        return update_claude_config(project_path)

    print()
    print("MCP Configuration")
    print("-" * 40)
    print("Would you like to configure Claude Code to use AgentHub?")
    print()
    print("Options:")
    print(f"  1. Auto-configure (update {CLAUDE_CONFIG_FILE})")
    print("  2. Show config (I'll set it up manually)")
    print("  3. Skip")
    print()

    choice = input("Choose [1/2/3]: ").strip()

    if choice == "1":
        if update_claude_config(project_path):
            print(f"Updated {CLAUDE_CONFIG_FILE}")
            print("Restart Claude Code to use the new MCP server.")
            return True
        else:
            print("Failed to update config. Please set up manually.")
            print_mcp_config(project_path)
            return False
    elif choice == "2":
        print_mcp_config(project_path)
        return True

    return False


def detect_project_type(project_path: str) -> dict:
    """Detect the type of project and its characteristics.

    Returns:
        Dict with 'type', 'name', 'module_name', 'ignore_patterns'.
    """
    project_path = Path(project_path).resolve()
    project_name = project_path.name

    # Convert to valid Python module name
    module_name = project_name.lower().replace("-", "_").replace(" ", "_")

    # Default ignore patterns
    ignore_patterns = [
        "__pycache__", ".git", "node_modules", ".venv", "venv",
        "dist", "build", ".pytest_cache", ".mypy_cache", "*.egg-info",
    ]

    # Detect project type
    project_type = "generic"

    # Check for Python project
    if (project_path / "pyproject.toml").exists() or \
       (project_path / "setup.py").exists() or \
       (project_path / "requirements.txt").exists():
        project_type = "python"
        ignore_patterns.extend(["*.pyc", "*.pyo", "htmlcov", ".tox"])

    # Check for Node.js project
    if (project_path / "package.json").exists():
        project_type = "nodejs" if project_type == "generic" else f"{project_type}+nodejs"
        ignore_patterns.extend([".next", "coverage", ".turbo", ".vercel"])

    # Check for Next.js specifically
    if (project_path / "next.config.js").exists() or \
       (project_path / "next.config.mjs").exists():
        project_type = "nextjs"

    # Check for monorepo
    if (project_path / "pnpm-workspace.yaml").exists() or \
       (project_path / "lerna.json").exists():
        project_type = "monorepo"

    return {
        "type": project_type,
        "name": project_name,
        "module_name": module_name,
        "ignore_patterns": ignore_patterns,
    }


def create_agents_file(project_path: str, project_info: dict) -> Path:
    """Create the project_agents.py file from template.

    Args:
        project_path: Path to the project.
        project_info: Dict from detect_project_type().

    Returns:
        Path to the created file.
    """
    project_path = Path(project_path).resolve()
    agents_file = project_path / f"{project_info['module_name']}_agents.py"

    # Format the template
    ignore_patterns_str = repr(project_info["ignore_patterns"])
    content = AGENTS_FILE_TEMPLATE.format(
        project_name=project_info["name"],
        module_name=project_info["module_name"],
        project_name_lower=project_info["module_name"],
        ignore_patterns=ignore_patterns_str,
    )

    agents_file.write_text(content)
    return agents_file


def create_agenthubignore(project_path: str) -> Path:
    """Create .agenthubignore file.

    Args:
        project_path: Path to the project.

    Returns:
        Path to the created file.
    """
    project_path = Path(project_path).resolve()
    ignore_file = project_path / ".agenthubignore"

    # Don't overwrite if exists
    if not ignore_file.exists():
        ignore_file.write_text(AGENTHUBIGNORE_TEMPLATE)

    return ignore_file


def setup_project(
    project_path: str = ".",
    auto_mcp: bool = True,
    skip_api_key_check: bool = False,
    verbose: bool = True,
) -> dict:
    """One-command project setup for AgentHub.

    This is the main entry point for `agenthub init`.

    Args:
        project_path: Path to initialize. Defaults to current directory.
        auto_mcp: Whether to automatically configure MCP for Claude Code.
        skip_api_key_check: Skip API key verification.
        verbose: Print progress messages.

    Returns:
        Dict with setup results including created files.

    Example:
        $ agenthub init              # Initialize current directory
        $ agenthub init /path/to/dir # Initialize specific directory
    """
    project_path = Path(project_path).resolve()
    results = {
        "success": False,
        "project_path": str(project_path),
        "files_created": [],
        "warnings": [],
        "errors": [],
    }

    def log(msg: str) -> None:
        if verbose:
            print(msg)

    # Validate project path
    if not project_path.exists():
        results["errors"].append(f"Path does not exist: {project_path}")
        return results

    if not project_path.is_dir():
        results["errors"].append(f"Not a directory: {project_path}")
        return results

    log(f"\n{'='*60}")
    log(f"AgentHub Init: {project_path.name}")
    log(f"{'='*60}\n")

    # Step 1: Detect project type
    log("Detecting project type...")
    project_info = detect_project_type(str(project_path))
    log(f"  Type: {project_info['type']}")
    log(f"  Name: {project_info['name']}")

    # Step 2: Check for existing agents file
    agents_file = project_path / f"{project_info['module_name']}_agents.py"
    if agents_file.exists():
        log(f"\n  Found existing agents file: {agents_file.name}")
        log("  Skipping agents file creation (use --force to overwrite)")
        results["warnings"].append(f"Agents file already exists: {agents_file}")
    else:
        log(f"\nCreating agents file: {project_info['module_name']}_agents.py")
        created = create_agents_file(str(project_path), project_info)
        results["files_created"].append(str(created))
        log(f"  Created: {created.name}")

    # Step 3: Create .agenthubignore
    ignore_file = project_path / ".agenthubignore"
    if ignore_file.exists():
        log("  Found existing .agenthubignore")
    else:
        log("Creating .agenthubignore...")
        created = create_agenthubignore(str(project_path))
        results["files_created"].append(str(created))
        log(f"  Created: {created.name}")

    # Step 4: Check API keys (optional)
    if not skip_api_key_check:
        log("\nChecking API keys...")
        keys = check_api_keys(str(project_path))
        if keys["anthropic"]:
            log("  ANTHROPIC_API_KEY: Found")
        elif keys["openai"]:
            log("  OPENAI_API_KEY: Found")
        else:
            log("  No API keys found")
            results["warnings"].append("No API keys found. Set ANTHROPIC_API_KEY or OPENAI_API_KEY")

    # Step 5: Save project path to global config
    log("\nSaving project configuration...")
    set_current_project(str(project_path))
    log(f"  Set as current project in ~/.agenthub/config.json")

    # Step 6: Configure MCP for Claude Code
    if auto_mcp:
        log("\nConfiguring MCP for Claude Code...")
        if update_claude_config(str(project_path)):
            log(f"  Updated {CLAUDE_CONFIG_FILE}")
            log("  Restart Claude Code to use AgentHub MCP tools")
        else:
            results["warnings"].append("Failed to update Claude Code config")

    # Done!
    results["success"] = True

    log(f"\n{'='*60}")
    log("AgentHub initialization complete!")
    log(f"{'='*60}")
    log(f"\nNext steps:")
    log(f"  1. Review {project_info['module_name']}_agents.py")
    log(f"  2. Add custom Tier A agents if needed")
    log(f"  3. Restart Claude Code to enable MCP tools")
    log(f"  4. Use AgentHub with: from {project_info['module_name']}_agents import create_hub")
    log("")

    return results
